<template>
  <div class="h-full w-full bg-gods bg-contain bg-top bg-no-repeat">
    <!--    <div class="flex justify-center bg-black/20">-->
    <!--      <div-->
    <!--        class="flex w-full flex-col justify-between p-6 md:w-[75rem] md:flex-row"-->
    <!--      >-->
    <!--        <img src="/images/logo-horizontal.svg " class="h-[60px]" />-->
    <!--        <div class="mt-4 flex justify-end self-center md:mt-0">-->
    <!--          <img src="/icons/facebook.svg" class="mr-2 h-[24px] w-[24px]" />-->
    <!--          <img src="/icons/instagram.svg" class="mr-2 h-[24px] w-[24px]" />-->
    <!--          <img src="/icons/twitter.svg" class="mr-2 h-[24px] w-[24px]" />-->
    <!--          <img src="/icons/youtube.svg" class="mr-2 h-[24px] w-[24px]" />-->
    <!--          <img src="/icons/github.svg" class="mr-2 h-[24px] w-[24px]" />-->
    <!--          <img src="/icons/tiktok.png" class="h-[24px] w-[24px]" />-->
    <!--        </div>-->
    <!--      </div>-->
    <!--    </div>-->
    <div class="flex justify-center md:mt-[8rem]">
      <div class="flex w-full flex-col justify-center md:w-[100rem]">
        <div class="flex flex-col-reverse p-4 md:flex md:flex-row md:p-0">
          <div class="w-full md:w-[75rem]">
            <div
              class="font-akira hidden w-full p-0 text-[2.5rem] font-black md:block md:text-[2.5rem]"
            >
              <span class="text-center"> MythWeaver </span>
            </div>
            <img
              src="/app-screenshot-1.png"
              class="mt-4 rounded-xl md:mt-12 md:h-[30rem]"
            />
            <div class="mt-2 text-center text-gray-400">
              (the character shown here was generated by MythWeaver)
            </div>
          </div>
          <div class="md:ml-12">
            <div class="my-6 w-full md:hidden">
              <img
                src="/images/logo-horizontal.svg"
                class="mx-auto h-[100px]"
              />
            </div>

            <MailingList
              id="mailing"
              title="Generate engaging D&D characters in realtime"
              subtitle="MythWeaver uses generative AI to create unique TTRPG characters with
    portraits, interesting backstories, looks and personalities."
            />
          </div>
        </div>
      </div>
    </div>

    <div class="bg-dragon2 bg-cover bg-top bg-no-repeat p-4 md:h-[120rem]">
      <div class="mt-[2rem] md:mt-[10rem]">
        <div class="mb-4 text-center text-[2.5rem] md:text-[3.5rem]">
          What can it do?
        </div>
        <div class="flex justify-center">
          <div
            class="grid w-full grid-cols-1 flex-col justify-between gap-8 md:w-[100rem] md:grid-cols-3 md:flex-row md:p-12"
          >
            <HighlightedItem
              title="Conjure Unique Characters"
              image="/app-screenshot-2.png"
              subtitle="with portraits and engaging backstories"
            >
              <div class="text-xl">
                <div class="text-3xl text-gray-400">Alden</div>
                <div class="text-gray-500">The Human Wizard</div>

                <div class="mt-4 text-xl">
                  Conjuring characters like Alden here, with intricate
                  backstories, personalities, looks and portraits is as easy as
                  clicking a button.
                </div>
              </div>
            </HighlightedItem>
            <HighlightedItem
              title="Exciting Loot & Quests"
              image="/app-screenshot-3.png"
              subtitle="with campaign specific content"
            >
              <div class="text-xl">
                MythWeaver generates contextually aware treasure & loot based on
                your campaign and the level of your party.
              </div>
            </HighlightedItem>
            <HighlightedItem
              title="Unlimited Customizability"
              image="/app-screenshot-4.png"
              subtitle="elf bard innkeeper with a dark past? no problem."
            >
              <div class="text-xl">
                Our AI engine takes in your custom inputs and generates you
                content to fit! You can also edit the generated content to your
                liking.
              </div>
            </HighlightedItem>
          </div>
        </div>

        <div
          class="font-akira mt-[10rem] text-center text-[36px] md:text-[52px]"
        >
          Hate Taking Notes?
        </div>

        <div
          class="font-akira text-center text-[24px] text-gray-400 md:text-[32px]"
        >
          We've got you covered.
        </div>

        <div
          class="font-quicksand mx-auto mt-4 text-center text-[22px] leading-[30px] text-gray-400 md:w-[60rem]"
        >
          MythWeaver transcribes your sessions in real-time, allowing you to
          focus on your game. Best of all, it's a computer, so it doesn't forget
          stuff, and you can easily search your campaign history! It even keeps
          your past sessions in mind when generating new content for your
          campaign.
        </div>

        <div class="mx-auto rounded-xl bg-black/75 text-green-400 md:w-[90rem]">
          <Typewriter
            class="mt-6 p-5 md:h-[43rem] md:w-[30rem]"
            :speed="25"
            :content="`Grog: I approach the towering, ominous door, its wooden planks older than time itself, creaking as I lay my hand upon it. I push it open, my muscles bulging, and... it squeaks?
<np>
Everyone: (Laughs)
<np>
Grog: Alright, not exactly the dramatic scene I was going for, but let's roll with it. I look around; what do I see?
<np>
DM: The room is largely empty, but in the center, there's a small, round table. Sitting atop it is a single muffin.
<np>
Quill: Wait, wait, a muffin? That's it? Are you sure it's not a magical muffin?
<np>
DM: Roll an Arcana check, Quill.
<np>
Quill: (Dice rolling) I got a 4.
<np>
DM: It's a very ordinary muffin.
<np>
Grog: I eat the muffin.
<np>
DM: Alright, you consume the muffin. It's blueberry.
<np>
Quill: I can't believe we just did a magic check on a muffin.
<np>
Everyone: (Laughs)
<np>
DM: Welcome to Dungeons and Dragons!`"
          />
        </div>
      </div>
    </div>

    <div
      class="flex w-full justify-center bg-hydra bg-auto bg-top bg-no-repeat md:h-[80rem] md:bg-cover"
    >
      <div class="w-full self-center p-4 md:w-[65rem] md:p-0">
        <MailingList
          title="Join our party!"
          subtitle="Don't miss out on something special. Join our mailing list to be notified of special early access opportunities, events, launch dates & more!"
          special-offer
        />
      </div>
    </div>

    <div
      class="relative flex h-[70rem] justify-center bg-gods bg-cover bg-top bg-no-repeat p-12 md:mt-[12rem] md:h-[60rem]"
    >
      <div
        class="absolute left-0 top-0 flex h-full w-full justify-center bg-gradient-to-b from-surface via-transparent to-surface"
      >
        <div
          class="mt-[1rem] flex w-full flex-col-reverse justify-between p-4 md:w-[75rem] md:flex-row md:p-0"
        >
          <div class="self-center">
            <div class="font-akira text-[2.25rem] md:text-[4rem]">
              About the developer
            </div>
            <div class="font-akira text-[1.75rem] text-gray-400 md:text-[2rem]">
              Austin Zurfluh
            </div>

            <div class="font-quicksand mt-6 text-[24px] leading-[30px]">
              Hey, I'm Austin! I'm a software engineer and entrepreneur with a
              passion for Dungeons & Dragons and TTRPGs in general. I've been
              playing D&D for more than 7 years now, and recently got very
              excited about the idea of using AI to help DMs and players alike.

              <br /><br />
              I've been blessed with the support of my family and friends to go
              after this crazy dream of mine, and I'm excited to share it with
              you all soon!

              <br /><br />
              If you want to get in touch, feel free to reach out to me, I'd
              love to chat!
            </div>
          </div>
          <div class="mb-8 flex w-full justify-center self-center">
            <img
              src="/images/austin.jpg"
              class="h-auto w-[30rem] rounded-full md:mb-0 md:ml-24"
            />
          </div>
        </div>
      </div>
    </div>

    <div class="mt-[2rem] flex justify-center p-4 md:h-[50rem]">
      <div class="mt-[1rem] flex w-full justify-between md:w-[75rem]">
        <div class="self-center">
          <MailingList
            title="Don't go, we need your help!"
            subtitle="You don't want to miss out on the exclusive benefits of our mailing list!"
          />
        </div>
      </div>
    </div>

    <div class="flex h-[4rem] justify-center border-t border-gray-700">
      <div class="font-quicksand self-center text-[14px]">
        © 2023 MythWeaver. All rights reserved.
      </div>
    </div>
  </div>
</template>
<script setup lang="ts">
import HighlightedItem from "@/components/HighlightedItem.vue";
import Typewriter from "@/components/Typewriter.vue";
import MailingList from "@/components/MailingList.vue";
</script>
