FROM node:20-alpine AS builder
WORKDIR /app
COPY api/package*.json ./
COPY api/yarn.lock ./
RUN yarn install
RUN yarn prisma generate
COPY api .
RUN yarn run build

FROM node:20-alpine AS server
WORKDIR /app
COPY package* ./
RUN yarn install --production
COPY --from=builder ./app/public ./public
COPY --from=builder ./app/build ./build
EXPOSE 8000
CMD ["npm", "start"]